services:
  director:
    networks:
      - bacula-backend
      - bacula-uplink

networks:
  bacula-backend:
    external: true
    name: conectaeduca-bacula_bacula-backend
  bacula-uplink:
    external: true
    name: conectaeduca-bacula_bacula-uplink
