services:
  wazuh.manager:
    ports: !override
      - "${CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS:?defina CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS}:${CONECTAEDUCA_WAZUH_AGENT_PORT:-1514}:1514/tcp"
      - "${CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS:?defina CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS}:${CONECTAEDUCA_WAZUH_SYSLOG_PORT:-5514}:514/udp"
    volumes:
      - ./.runtime/wazuh_manager_vm.conf:/wazuh-config-mount/etc/ossec.conf:ro
