services:
  wazuh.manager:
    ports: !override
      - "${CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS:?defina CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS}:${CONECTAEDUCA_WAZUH_AGENT_PORT:-1514}:1514/tcp"

  wazuh.indexer:
    ports: !override []

  wazuh.dashboard:
    ports: !override
      - "${CONECTAEDUCA_WAZUH_DASHBOARD_BIND_ADDRESS:?defina CONECTAEDUCA_WAZUH_DASHBOARD_BIND_ADDRESS}:${CONECTAEDUCA_WAZUH_DASHBOARD_PORT:-443}:5601/tcp"
