# Baseado no gerador oficial Wazuh Docker v4.14.7.
name: conectaeduca-wazuh-certs

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.4@sha256:369b4d58509aab074b188596870c81584f7120e653d9ef83c591f0f785dcf325
    hostname: wazuh-certs-generator
    environment:
      CERT_TOOL_VERSION: "4.14"
    volumes:
      - ./.runtime/certs:/certificates
      - ./config/certs.yml:/config/certs.yml:ro
