#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"; VMS_DIR="$(cd -P "$SCRIPT_DIR/.." && pwd -P)"; source "$VMS_DIR/lib/comum.sh"
CONFIG=""; MODE=check; WITH_WAZUH=0; WITH_OPENBAO=0; WITH_FERRET=0
while (($#)); do case "$1" in --config) CONFIG="${2:-}"; shift 2;; --check) MODE=check; shift;; --apply) MODE=apply; shift;; --with-wazuh) WITH_WAZUH=1; shift;; --with-openbao) WITH_OPENBAO=1; shift;; --with-ferret) WITH_FERRET=1; shift;; --all-services) WITH_WAZUH=1; WITH_OPENBAO=1; WITH_FERRET=1; shift;; --self-test) ce_valid_ipv4 192.0.2.20 && echo 'SELF_TEST_INTERNA_FASE1=APROVADO'; exit;; *) exit 64;; esac; done
[[ -r "$CONFIG" ]] || { echo "ERRO: --config obrigatório" >&2; exit 64; }; ROOT="$(ce_require_project_root)"; [[ "$(hostname)" == conectaeduca-interna ]] || { echo "ERRO: execute em CE-UBUNTU-INT" >&2; exit 1; }
DB_BIND="$(ce_cfg_required CONECTAEDUCA_DB_BIND_ADDRESS "$CONFIG")"; DB_PORT="$(ce_cfg_get CONECTAEDUCA_DB_PORT "$CONFIG")"; DB_PORT="${DB_PORT:-3306}"; ROOT_SECRET="$(ce_cfg_required CONECTAEDUCA_DB_ROOT_PASSWORD_FILE "$CONFIG")"; APP_SECRET="$(ce_cfg_required CONECTAEDUCA_DB_PASSWORD_FILE "$CONFIG")"
ce_valid_ipv4 "$DB_BIND" || exit 64; ce_port_valid "$DB_PORT" || exit 64; for c in docker openssl python3; do command -v "$c" >/dev/null || { echo "ERRO: comando ausente: $c" >&2; exit 1; }; done; docker info >/dev/null 2>&1 || exit 1
if [[ "$MODE" == apply ]]; then for f in "$ROOT_SECRET" "$APP_SECRET"; do install -d -m 0700 "$(dirname "$f")"; done; if docker volume inspect conectaeduca-mariadb_mariadb_data >/dev/null 2>&1 && { [[ ! -s "$ROOT_SECRET" ]] || [[ ! -s "$APP_SECRET" ]]; }; then echo 'ERRO: volume MariaDB existente com secret ausente.' >&2; exit 1; fi; [[ -s "$ROOT_SECRET" ]] || { umask 077; openssl rand -hex 32 >"$ROOT_SECRET"; }; [[ -s "$APP_SECRET" ]] || { umask 077; openssl rand -hex 32 >"$APP_SECRET"; }; chmod 600 "$ROOT_SECRET" "$APP_SECRET"; fi
[[ -s "$ROOT_SECRET" && -s "$APP_SECRET" ]] || { echo "ERRO: secrets MariaDB ausentes" >&2; exit 1; }
export CONECTAEDUCA_DB_BIND_ADDRESS="$DB_BIND" CONECTAEDUCA_DB_PORT="$DB_PORT" CONECTAEDUCA_DB_ROOT_PASSWORD_FILE="$ROOT_SECRET" CONECTAEDUCA_DB_PASSWORD_FILE="$APP_SECRET"; DB_BASE="$ROOT/deploy/interna/mariadb/compose.yml"; DB_HOST="$ROOT/deploy/interna/mariadb/compose.host.yml"; docker compose -f "$DB_BASE" -f "$DB_HOST" config >/dev/null
if [[ "$MODE" == apply ]]; then docker compose -f "$DB_BASE" -f "$DB_HOST" up -d mariadb; cid="$(docker compose -f "$DB_BASE" -f "$DB_HOST" ps -q mariadb)"; [[ -n "$cid" ]] || exit 1; ce_wait_container_health "$cid" 180 || exit 1; fi
echo 'MARIADB_INTERNA=PRONTO'
if (( WITH_WAZUH )); then MGR="$(ce_cfg_required CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS "$CONFIG")"; DASH="$(ce_cfg_required CONECTAEDUCA_WAZUH_DASHBOARD_BIND_ADDRESS "$CONFIG")"; export CONECTAEDUCA_WAZUH_MANAGER_BIND_ADDRESS="$MGR" CONECTAEDUCA_WAZUH_DASHBOARD_BIND_ADDRESS="$DASH"; export CONECTAEDUCA_WAZUH_AGENT_PORT="$(ce_cfg_get CONECTAEDUCA_WAZUH_AGENT_PORT "$CONFIG")" CONECTAEDUCA_WAZUH_ENROLLMENT_PORT="$(ce_cfg_get CONECTAEDUCA_WAZUH_ENROLLMENT_PORT "$CONFIG")" CONECTAEDUCA_WAZUH_DASHBOARD_PORT="$(ce_cfg_get CONECTAEDUCA_WAZUH_DASHBOARD_PORT "$CONFIG")"; : "${CONECTAEDUCA_WAZUH_AGENT_PORT:=1514}"; : "${CONECTAEDUCA_WAZUH_ENROLLMENT_PORT:=1515}"; : "${CONECTAEDUCA_WAZUH_DASHBOARD_PORT:=443}"; [[ "$MODE" == apply ]] && { bash "$SCRIPT_DIR/12-preparar-wazuh-runtime-vm.sh"; bash "$ROOT/scripts/implantacao/validar_wazuh_operacional.sh" --perfil vm --subir-se-necessario; } || echo 'WAZUH_INTERNA=CHECK_SOLICITADO'; fi
if (( WITH_OPENBAO )); then [[ "$MODE" == apply ]] && bash "$SCRIPT_DIR/14-preparar-openbao-vm.sh" --apply || bash "$SCRIPT_DIR/14-preparar-openbao-vm.sh" --check; fi
if (( WITH_FERRET )); then [[ "$MODE" == apply ]] && bash "$SCRIPT_DIR/16-preparar-ferret-vm.sh" --apply || bash "$SCRIPT_DIR/16-preparar-ferret-vm.sh" --check; fi
echo 'INTERNA_FASE1=CONCLUIDA'; echo "DB_APP_SECRET_PATH=$APP_SECRET"; echo 'IMPORTANTE=TRANSFERIR_O_MESMO_DB_APP_SECRET_COM_SEGURANCA_PARA_DMZ'
