#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"; VMS_DIR="$(cd -P "$SCRIPT_DIR/.." && pwd -P)"; source "$VMS_DIR/lib/comum.sh"
CONFIG=""; while (($#)); do case "$1" in --config) CONFIG="${2:-}"; shift 2;; --self-test) echo 'SELF_TEST_CHECKPOINT_INTERNA=APROVADO'; exit;; *) exit 64;; esac; done
[[ -r "$CONFIG" ]] || exit 64; ROOT="$(ce_require_project_root)"; [[ "$(hostname)" == conectaeduca-interna ]] || exit 1; STAMP="$(date +%Y%m%d-%H%M%S)"; OUT="$HOME/Downloads/conectaeduca-checkpoint-CE-UBUNTU-INT-$STAMP.txt"; : >"$OUT"; ce_set_report "$OUT"; ce_section 'CE-UBUNTU-INT / checkpoint fase 1'; ce_emit "HOSTNAME=$(hostname)"; ce_emit "HEAD=$(git -C "$ROOT" rev-parse HEAD)"
DB_BIND="$(ce_cfg_required CONECTAEDUCA_DB_BIND_ADDRESS "$CONFIG")"; DB_PORT="$(ce_cfg_get CONECTAEDUCA_DB_PORT "$CONFIG")"; DB_PORT="${DB_PORT:-3306}"; ss -ltn 2>/dev/null | grep -Fq "$DB_BIND:$DB_PORT" && ce_ok "MariaDB binding $DB_BIND:$DB_PORT" || ce_fail 'MariaDB binding ausente'
cid="$(docker ps -q --filter label=com.docker.compose.project=conectaeduca-mariadb --filter label=com.docker.compose.service=mariadb 2>/dev/null | head -1 || true)"; if [[ -n "$cid" ]]; then state="$(docker inspect -f '{{.State.Status}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$cid")"; ce_emit "MARIADB_STATE=$state"; [[ "$state" == running\|healthy ]] && ce_ok 'MariaDB healthy' || ce_fail 'MariaDB não healthy'; else ce_fail 'MariaDB container ausente'; fi
map="$(cat /proc/sys/vm/max_map_count 2>/dev/null || echo 0)"; (( map >= 262144 )) && ce_ok "vm.max_map_count=$map" || ce_fail "vm.max_map_count=$map"; docker ps --format '{{.Names}}' | grep -q 'wazuh' && ce_ok 'Wazuh presente' || ce_warn 'Wazuh ainda não ativo'; docker ps --format '{{.Names}}' | grep -q 'ferret' && ce_ok 'Ferret presente' || ce_warn 'Ferret ainda não ativo'; docker ps --format '{{.Names}}' | grep -q 'openbao' && ce_ok 'OpenBao presente' || ce_warn 'OpenBao ainda não ativo'
ce_emit "FAILURES=$CE_FAILURES"; ce_emit "WARNINGS=$CE_WARNINGS"; ce_emit "ARQUIVO_SAIDA=$OUT"; (( CE_FAILURES==0 )) && { ce_emit 'CHECKPOINT_INTERNA=APROVADO'; exit 0; }; ce_emit 'CHECKPOINT_INTERNA=REPROVADO'; exit 1
