#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"; VMS_DIR="$(cd -P "$SCRIPT_DIR/.." && pwd -P)"; source "$VMS_DIR/lib/comum.sh"
CONFIG=""; MODE=check
while (($#)); do case "$1" in --config) CONFIG="${2:-}"; shift 2;; --check) MODE=check; shift;; --apply) MODE=apply; shift;; --self-test) TEST_ROOT="${PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || true)}"; [[ -f "$TEST_ROOT/deploy/dmz/compose.vm.yml" ]] && echo 'SELF_TEST_DMZ_FASE1=APROVADO'; exit;; *) exit 64;; esac; done
[[ -r "$CONFIG" ]] || exit 64; ROOT="$(ce_require_project_root)"; [[ "$(hostname)" == conectaeduca-dmz ]] || { echo "ERRO: execute em CE-UBUNTU-DMZ" >&2; exit 1; }
keys=(CONECTAEDUCA_WAF_BIND_ADDRESS CONECTAEDUCA_DB_HOST CONECTAEDUCA_DB_PASSWORD_FILE CONECTAEDUCA_PRIVATE_KEY_FILE CONECTAEDUCA_PUBLIC_KEY_FILE CONECTAEDUCA_WAF_TLS_CERT_FILE CONECTAEDUCA_WAF_TLS_KEY_FILE CONECTAEDUCA_APP_URL CONECTAEDUCA_STACK_SECRET_GID); for k in "${keys[@]}"; do v="$(ce_cfg_required "$k" "$CONFIG")"; printf -v "$k" '%s' "$v"; export "$k"; done; export CONECTAEDUCA_DB_PORT="$(ce_cfg_get CONECTAEDUCA_DB_PORT "$CONFIG")"; : "${CONECTAEDUCA_DB_PORT:=3306}"; export CONECTAEDUCA_HTTP_PORT="$(ce_cfg_get CONECTAEDUCA_HTTP_PORT "$CONFIG")"; : "${CONECTAEDUCA_HTTP_PORT:=80}"; export CONECTAEDUCA_HTTPS_PORT="$(ce_cfg_get CONECTAEDUCA_HTTPS_PORT "$CONFIG")"; : "${CONECTAEDUCA_HTTPS_PORT:=443}"
FILES=(compose.yml compose.database.yml compose.app-secrets.yml compose.waf.yml compose.waf-tls.yml compose.waf-policy.yml compose.host.yml compose.vm.yml); args=(); for f in "${FILES[@]}"; do args+=( -f "$ROOT/deploy/dmz/$f" ); done; for f in "$CONECTAEDUCA_DB_PASSWORD_FILE" "$CONECTAEDUCA_PRIVATE_KEY_FILE" "$CONECTAEDUCA_PUBLIC_KEY_FILE" "$CONECTAEDUCA_WAF_TLS_CERT_FILE" "$CONECTAEDUCA_WAF_TLS_KEY_FILE"; do [[ -s "$f" ]] || { echo "ERRO: runtime ausente: $f" >&2; exit 1; }; done; docker info >/dev/null 2>&1 || exit 1; docker compose "${args[@]}" config >/dev/null
[[ "$MODE" == check ]] && { echo 'DMZ_COMPOSE_VM=VALIDO'; exit 0; }; docker compose "${args[@]}" build php nginx waf; docker compose "${args[@]}" up -d; for svc in php nginx waf; do cid="$(docker compose "${args[@]}" ps -q "$svc")"; [[ -n "$cid" ]] || exit 1; ce_wait_container_health "$cid" 180 || exit 1; done; echo 'DMZ_FASE1=CONCLUIDA'
